#ifndef COEUS_CSL_INTERPRETER_CSL_CHUNK_TYPE_H
#define COEUS_CSL_INTERPRETER_CSL_CHUNK_TYPE_H

enum CSLChunkType
{
	INVALID_CHUNK_TYPE = -1,

	CHUNK_TYPE_COMMAND,
	CHUNK_TYPE_FUNC,
	CHUNK_TYPE_OP,
	CHUNK_TYPE_STMT,

	CHUNK_TYPE_VAR,

	CHUNK_TYPE_CONST_STRING,
	CHUNK_TYPE_CONST_INT,
	CHUNK_TYPE_CONST_FLOAT,

	NUM_CHUNK_TYPES
};

#endif // COEUS_CSL_INTERPRETER_CSL_CHUNK_TYPE_H