#ifndef COEUS_CSL_INTERPRETER_CSL_VAR_TYPE_H
#define COEUS_CSL_INTERPRETER_CSL_VAR_TYPE_H

enum CSLVarType
{
	INVALID_VAR_TYPE = -1,

	VAR_TYPE_STRING,
	VAR_TYPE_INT,
	VAR_TYPE_FLOAT,

	NUM_VAR_TYPES
};

#endif // COEUS_CSL_INTERPRETER_CSL_VAR_TYPE_H